/* tslint:disable */
/* eslint-disable */
/**
 * 后浪API文档
 * 后浪项目接口文档
 *
 * The version of the OpenAPI document: v1
 * Contact: contact@yourapp.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export * from "./api";
export * from "./configuration";

