import type { Metadata } from "next";
import "./globals.css";
import { Poppins } from "next/font/google";
import "@arco-design/web-react/dist/css/arco.css";
import { Provider } from "jotai";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const roboto = Poppins({
  weight: ["400", "500", "700"],
  display: "swap",
  subsets: ["latin"],
});
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${roboto.className}`}>
      <body>
        <Provider>
          <div className="w-screen h-screen">{children}</div>
        </Provider>
      </body>
    </html>
  );
}
